### ISSUE TITLE
CSS .fa en conflit avec tpl/default/css/shaarli.min.css

### ISSUE THREAD

**Issue by AlainRnet** [immanuelfodor/shaarli-markdown-toolbar#3]
La règle de ce fichier ".fa{font:normal normal normal 14px/1 FontAwesome;} est en conflit avec la règle du fichier cité en titre ".fa{font:normal normal normal 14px/1 ForkAwesome;}
L'icône Shaarli en pied de page ne s'affiche plus.

**Comment by immanuelfodor** [comment]
Hi, thanks for the issue! If I understand correctly, the footer should contain a Shaarli icon that is not displayed as some CSS rule overrides it from the plugin, right? I'm using the Material theme, and I tried to disable the plugin but there is still no icon in the footer:

![image](https://user-images.githubusercontent.com/21174107/91653843-5af89c80-eaa4-11ea-8fde-631c761198be.png)

Maybe on the default theme?

**Comment by AlainRnet** [comment]
Yes, it was, but I cannot reproduce the bug. Is it because I would have updated it? I’m currently with Shaarli v. 0.11.1 but I don’t remember if it was this version in April when I opened this bug ticket. Sorry.

**Comment by immanuelfodor** [comment]
I also tried with the default theme, it seems to be working now. No problem, thanks for reporting it! :) I released a new version that is compatible with the newest Shaarli (there was a huge routing rewrite lately) if you're about to upgrade, it should work. Closing this one.
